#!/bin/bash
#
# https://coral.ai/docs/accelerator/get-started

# Step 1A
echo "deb https://packages.cloud.google.com/apt coral-edgetpu-stable main" | sudo tee /etc/apt/sources.list.d/coral-edgetpu.list
curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
sudo apt-get update
sudo apt-get install libedgetpu1-std

# Step 2A
sudo apt-get install python3-pycoral

