#!/bin/bash

apt-get install update
apt-get install upgrade

apt-get install vim
apt-get install gpsd gpsd-clients python3-gps
apt-get install python3-smbus i2c-tools git-core
apt-get install hostapd dnsmasq iptables-persistent

systemctl disable serial-getty@ttyAMA0
systemctl stop serial-getty@ttyAMA0

systemctl enable gpsd.socket
systemctl start gpsd.socket

cmd="/bin/cp"

#${cmd} 01-lidar.rules
${cmd} dhcpcd.conf /etc
${cmd} dnsmasq.conf /etc
${cmd} iptables.ipv4.nat /etc
#${cmd} ntp.conf 
${cmd} rc.local /etc
${cmd} sysctl.conf /etc
${cmd} gpsd /etc/default
${cmd} hostapd.conf /etc/hostapd
