#!/bin/bash
cmd="/bin/cp"

apt-get install update
apt-get install upgrade

apt-get install vim
apt-get install python3-smbus i2c-tools git

# WiFi Hotspot
apt-get install hostapd dnsmasq iptables-persistent
${cmd} hostapd.conf /etc/hostapd
systemctl unmask hostapd
systemctl enable hostapd
systemctl start hostapd

# GPS
apt-get install gpsd gpsd-clients python3-gps
${cmd} gpsd /etc/default
systemctl disable serial-getty@ttyAMA0
systemctl stop serial-getty@ttyAMA0
systemctl enable gpsd.socket
systemctl start gpsd.socket


#${cmd} 01-lidar.rules /etc/udev/rules.d
${cmd} dhcpcd.conf /etc
${cmd} dnsmasq.conf /etc
${cmd} iptables.ipv4.nat /etc
${cmd} rc.local /etc
${cmd} sysctl.conf /etc
